version: 2.1

orbs:
  # orb for jira integration
  jira: circleci/jira@1.3.1
  # orb for slack integration
  slack: circleci/slack@4.4.2

# Define the jobs we want to run for this project
jobs:
  # This "pull-and-build-containers" job will only run when the main branch receives update (as per our workflow)
  # We also want to be alerted if this job fails and also when it succeeds.
  pull-and-build-containers:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: SSH into server --> run deploy script
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP -p $PORT "./deploy.sh"
      # In the event the deployment has failed, alert the engineering team
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@DevTeam"
      # When there is a successful deployment, send a notification with a different template.
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - jira/notify 
      

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build-containers:
          context: 
            - Slack
          filters:
            branches:
              only:
                - main
          post-steps:
            - jira/notify